# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1d463f6b7bdfa1fdccd7319d3dbaa02b49a1934a382ca52c83ba7736fc52506fdd6fea6a80195ec76725dad6bb5fef8db56274b3042de0af3c9ab2e5d0ce551

test:
  secret_key_base: 67d2a740a74479c2fb26c85313cc585436cd389e5c80353687dffe7c69abe2756f3b8ca2a4f0fc1e675a099d9694079aaa2d7bfc1ac28cfe0ae24582a1897a5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
